### PR TITLE
VAT Report & Purchase Tax Template

### PR DESCRIPTION
**Pull request by realespee**
* Fix Calculations with VAT Detailed Report
* Ship Purchase Tax Templates Customization to App

### CODE REVIEW

**Comment by realespee** [comment]
This branch was off develop, I think you deleted it.

**Comment by realespee** [comment]
I will fix the divergence and create a new PR

**Comment by realespee** [comment]
I deiced to merge locally so i could fix the conflict

**Comment by shakirpm** [comment]
Okay

**Pull request closed without merging**
